### ISSUE TITLE
Reserved Table for Json Document Storage, Queries, Import

### ISSUE THREAD

**Issue by twoxfh** [lana-k/sqliteviz#56]
@lana-k Would you consider having a table in the SQLite Database which is reserved for Json documents? Maybe first use case is to store queries.json file in the SQLite database as a reserved record. Another use case may be to import json documents so users can query hierarchical data sources. SQL.js has the JSON1 extension already built into 1.5 and this would allow everything to be bundled together.

**Comment by saaj** [comment]
I see two ideas here:

1. storing `queries.json` together with the database
2. JSON file import

JSON import
-----------
I like the idea of importing JSON files. Some Linux tools, for instance `smemstat`, only have JSON as a machine-readable output format option. JSON1 functions and recursive CTEs, indeed, should be sufficient for most cases of extracting data from the document(s) and JOINing them with other tables. 

What needs discovery here is how exactly should import work. A few questions and notes while I'm thinking along:
1. User should be able to provide a table name like with CSV. I don't think it needs to be a reserved table.
2. What's the table schema? Always `CREATE TABLE user_provided(document TEXT)`? It's probably fine.
3. Does single file always produce single row? Even if the root JSON type is `Array`? Probably it's better to keep the document on a single row because in case of support of item 4 it'll be confusing what corresponds to a row. 
4. What about [ndjson][1]? It's still quite niche, so first iteration is fine without it.

Looks clear enough. I can write an RFE for it.

Storing visualisations in the database
--------------------------------------
It sounds interesting. I would like to explore the use cases for it. When a separate "queries" file (i.e. import/export JSON config, which we, by the way, need a better name for; a collection of 2-tuples `[(SQL1, viz_cgf1), (SQL2, viz_cgf2), ...]` can be presets, bundle, or maybe even inquiries) isn't sufficient or convenient? Probably to give it to someone as single file, but if #41 is there, is there still a need for it?



[1]: http://ndjson.org/

**Comment by twoxfh** [comment]
I see the sqlite database as an analytical database instead of transactional. I see json documents being stored in a single column with meta information about the json documents in the others. For example select json from json_documents where name='queries' and then using the json1 extension on the result. This could greatly simplify dynamic loading of external json documents and import could still be straight forward like external csvs without a lot of processing.

**Comment by twoxfh** [comment]
I likely will close this issue, I do see a good benefit of everything being scripted. Given SQL being the only scripted language, possibly creating a JS function to return a dynamically fetched JSON document which is then used on insert of a record is a better approach. The user would first create a table and then insert data with one of the column values being the function.

**Comment by saaj** [comment]
> `select json from json_documents where name='queries'` [...]

I understand the use case then you want to query a document (with data) for visualisation (i.e. "JSON import" section in by message above). 

I don't understand how exactly you're going to use visualisation presets (SQL + Plotly settings) from the database itself. Currently there is an idea that single visualisation preset can be used for multiple datasets (i.e. SQL databases and/or collections of CSVs).

**Comment by saaj** [comment]
On fetching JSON documents. Single-valued (and aggregate also) SQLite functions should be [straighforward in `sql.js`][1]. I guess one could be a thin wrapper around [Fetch API][2]. I'd return to it later after JSON file import.

[1]: https://sql.js.org/documentation/Database.html#%255B%2522create_function%2522%255D
[2]: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by twoxfh** [comment]
My thoughts around a db function likely won't work due to the synchronous nature required on browsers that require asynchronous requests. An asynchronous function would just cause more confusion since you wouldn't know when the data loaded.

**Comment by saaj** [comment]
You're right, I missed the fact that `create_function` API is synchronous on the side of `sql.js`. At the same time [synchronous XHR seems still fine from the worker][1] so that could still work.


[1]: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests#example_synchronous_http_request_from_a_worker

**Comment by twoxfh** [comment]
@saaj will check out XHR from worker, not sure if @lana-k has a strong feeling either way.

@saaj can you explain how a visualization is used across multiple tables/csvs? Maybe I misunderstood.

**Comment by twoxfh** [comment]
@saaj thinking more about this, the create_function executes inside an existing worker, its more about what the project approach is to synchronous connections. Hopefully browsers wont kill them off, and is there a contribution @lana-k would accept.  Certainly XMLHttpRequest works, but likely there is a Vue component which may be preferred.

**Comment by twoxfh** [comment]
Closing issue, enabling wasm storage would be likey a better way to handle importing data.
